'''
- Even Fibonacci numbers -
"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."
(https://projecteuler.net/problem=2)
'''

def fibo(n):
    array = [1, 2]
    i=0
    while array[i]+array[i+1] < n:
        array.append(array[i]+array[i+1])
        i+=1
    return array

fibo_list = fibo(4000000)
print(fibo_list)
sum=0
for i in fibo_list:
    if i%2==0:
        sum += i
print(sum)